### ISSUE TITLE
[focal] Evaluate curated apps to do with debian vs flathub

### ISSUE THREAD

**Issue by jackpot51** [pop-os/repo-proprietary#19]
We have overlap in focal due to having both our proprietary repo and flathub out of the box. we can remove things from the proprietary repo as desired to reduce maintenance.

repo-curated-free:
- [x] Atom
- [ ] GitHub Desktop
- [ ] Mattermost
- [ ] Wire

repo-proprietary:
- [ ] Discord
- [ ] GitKraken
- [x] Google Chrome
- [ ] Plex
- [ ] Signal
- [ ] Slack
- [ ] Spotify
- [x] Visual Studio Code

**Comment by mmstick** [comment]
I believe we can eliminate these packages from the repo:

- Spotify
- Signal
- Gitkraken
- Mattermost
- Slack
- Wire

Things we could remove from Launchpad:

- DBeaver CE
- KeePassXC
- Lollypop

Things we should keep, because the flathub package isn't as usable

- Atom
- VS Code

Things which do not have a flatpak package:

- Natron
- GitHub Desktop
- Plex Media Server
- Sayonara
- Lutris
- GameHub

**Comment by WatchMkr** [comment]
@mmstick Can we maintain flatpak packages on Flathub for some of the packages in the "do not have" list? (Rather than .deb).

**Comment by jackpot51** [comment]
@WatchMkr maybe, but in some cases that may increase our maintenance burden.

**Comment by WatchMkr** [comment]
The slack flatpak on flathub still doesn't work for attachments. I'll keep monitoring, but that will need to be fixed or stick with our deb.

**Comment by jackpot51** [comment]
https://gist.github.com/jackpot51/d6d9a511dc15ad0fb6aad7208371c3e4

**Comment by WatchMkr** [comment]
@jackpot51 @mmstick 

Repo changes list. Very close to Michael's.

## Pop Repo

### Keep
Atom (Needs update)
Code
Github Desktop (Needs update)
Google Chrome Stable (update & add appstream data)
Natron
Plex Media Server (Needs update)
Slack (Needs update)

### Transition to Flatpak
Discord
Gitkraken
Mattermost
Signal
Spotify
Wire Desktop

## Launchpad

### Keep
Alacritty (Needs update)
Chromium (Needs update)
Eddy (Needs update)
Gamehub 
Happiness 
Lutris
Phoronix Test Suite (Needs update)
Popsicle
Steam

### Transition to Flatpak
Android Studio
DBeaver
GNOME Authenticator
KeepassXC
Lollypop

Peek

### Remove
GNOME Shell Pomodoro (In Ubuntu repo. Drop from Pop repo)
OpenSCAD (newest version in Ubuntu repo and Flathub)
Sayonara (Should be a Flatpak preferably by the developer)

**Comment by WatchMkr** [comment]
For discussion:

- Passbook (Do we need to maintain this one?)
- Geary... what to do with Geary?
- How are we transitioning users?

**Comment by jackpot51** [comment]
Proposal for transitioning from apt to flathub as a user repository:

APT package becomes a stub with the following contents, assuming this is a GUI application:

- The .desktop and icon files from the original package, so the application still shows up in GNOME.
- A script at the original location of the application's binary.

The script would be a template that would check if the flatpak is installed for the current user, and run it with the provided arguments. If it is not installed, it would direct the user to the Install page for the application in Pop Shop. If the user does not have a flatpak remote with the application available, behavior TBD.

Appstream data would be removed for the APT version so Pop!_Shop prioritizes the Flathub version and doesn't show the transitional package. I would like to produce the first transition example myself as a template

**Comment by WatchMkr** [comment]
Deb to Flatpak transition meeting conclusion:

- Copy debs to focal pop repo.
- Develop app that will notify users that the debs being replaced by flatpak will no longer receive updates (if they're installed)
- Clicking the notification opens a window describing the transition to Flatpak and linking the user to the Pop store to install the Flatpak version. Also suggest removing the deb.
- Continue notifying users weekly until the debs are no longer installed
- Provide the user the option to opt out of the notifications

**Comment by sosiristseng** [comment]
I tried Gitkraken (flatpak version). It ran fine but with a caveat: external editor was not selectable due to permission reasons. Thus I reverted to the deb version from the official website.
