### ISSUE TITLE
[focal] Steam is not installable 

### ISSUE THREAD

**Issue by leviport** [pop-os/repo-proprietary#21]
In Pop Shop, I see the Ubuntu (deb) source in the app named "Steam Installer" which is a Pop Pick. I also see an app just named "Steam" which only has flathub as a source.

Trying to install Steam Installer gives me this error:
![steam](https://user-images.githubusercontent.com/13512097/80639177-dd058580-8a1e-11ea-80c1-6c864bcaa9e0.png)

**Comment by jackpot51** [comment]
I'm deleting the old package. When it's done being deleted, this should be fixed

**Comment by leviport** [comment]
All better!

**Comment by jackpot51** [comment]
This should be fixed now, please verify
