### ISSUE TITLE
[focal] Dbeaver not installable

### ISSUE THREAD

**Issue by leviport** [pop-os/repo-proprietary#22]
Flathub source installs, Pop deb source gives me this error
![dbeaver](https://user-images.githubusercontent.com/13512097/80643098-c6622d00-8a24-11ea-9280-411e13615148.png)

**Comment by brs17** [comment]
It should be noted that the Pop deb is the default here.


Didn't mean to close the issue. :see_no_evil:

**Comment by jackpot51** [comment]
We need to edit dbeaver-ce
