### ISSUE TITLE
Signal-desktop and discord is outdated

### ISSUE THREAD

**Issue by cr-ashworks** [pop-os/repo-proprietary#23]
Hey all, great job with making pop os,
at the moment there are at least two versions of apps in the repo which don't work any more. 

There are newer releases of the app "discord", which is now 0.0.10 instead of 0.0.9 and also of the app signal-desktop which is now 1.34.1 instead of 1.29.6.
Thank you again.

**Comment by jacobgkau** [comment]
Discord is current as of https://github.com/pop-os/repo-proprietary/pull/28.

Signal is no longer included in this repo for current Pop!_OS versions (it has a feature-complete Flatpak version available and Pop will [offer to transition](https://github.com/pop-os/transition) after a release upgrade), but https://github.com/pop-os/repo-proprietary/pull/29 will update it to the latest release on Bionic where it's still in our repo.
