### ISSUE TITLE
Fix the Slack deb for 21.10

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/repo-proprietary#33]
carl@pop-os:~$ slack
ssh: Could not resolve hostname slack-master: Temporary failure in name resolution
rsync: did not see server greeting
rsync error: error starting client-server protocol (code 5) at main.c(1814) [Receiver=3.2.3]
FATAL[slack-getroles]: 'rsync --links --times -e ssh slack-master::slack/etc/roles.conf /var/cache/slack/_role_list' exited 5 at /usr/lib/slack/slack-getroles line 158.
FATAL[slack]: '/usr/lib/slack/slack-getroles' exited 5 at /usr/sbin/slack line 205.

**Comment by jackpot51** [comment]
Probably fixed in master but not released yet

**Comment by Izhar5528** [comment]
FATAL[slack-sync]: Could not mkpath cache dir '/var/cache/slack/roles/': FATAL[slack-sync]: mkdir /var/cache/slack/roles/: Permission denied at /usr/lib/slack/slack-sync line 136.
