### ISSUE TITLE
Discord package outdated

### ISSUE THREAD

**Issue by DanielPower** [pop-os/repo-proprietary#51]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
discord:
  Installed: (none)
  Candidate: 0.0.10
  Version table:
     0.0.10 500
        500 http://apt.pop-os.org/proprietary focal/main amd64 Packages

**Issue/Bug Description:**
Discord package is outdated. Latest version is 0.0.11. Since you cannot connect to the Discord servers with an outdated version (it simply gives you a window telling you to update), I would suggest dropping the package from your repos so that when users search the Pop Shop, they'll find the flatpak on Flathub, which is more actively maintained.

The current experience is that a user will install Discord from the Pop Shop, and will then be told it's outdated when they try to run it. New users in particular may not know that there is a dropdown menu from which they can download a more recent package from Flathub.

**Steps to reproduce (if you know):**
Download Discord from Pop repository using Pop Shop or apt.

**Expected behavior:**
Package should be up to date. Or defaulted to the flatpak.

**Other Notes:**

**Comment by jacobgkau** [comment]
> 0.0.24 is out and it broke the old one the old one same as always apparently

https://github.com/pop-os/repo-proprietary/pull/52 will update Discord to 0.0.24.

> EDIT: couldn't this be automated with a workflow or something? since this seems to be a recurrent issue

Theoretically, yes. A system would need to periodically check if Discord has released an update, and if it has, download it, get the checksum, and update the version number and checksum in the configuration file for building. Of course, you would be getting no QA if that was released automatically (also a security issue), so we'd probably want it to just open the PR automatically.

**Comment by mmstick** [comment]
Maybe Discord could focus on the Flatpak packaging since it's required by Steam OS anyway, and then we wouldn't have to import it.

**Comment by jacobgkau** [comment]
> Maybe Discord could focus on the Flatpak packaging since it's required by Steam OS anyway, and then we wouldn't have to import it.

I thought about recommending the Flatpak since it is currently up-to-date, but iirc, the reason it doesn't have feature parity with the .deb is because of the sandboxing. Discord allows monitoring for processes so it can display what game you're playing, how long you've been in-game, etc. Not sure if that's feasible with Flatpak, but it would be great if they could get it working.

**Comment by GDBlaster** [comment]
This is probably a limitation of flatpak that we cant get around

Not an expert so there might be some hacky way but its probably better to
not do this kind of things

**Comment by DanielPower** [comment]
I'm not an expert on the matter. But this sounds like the kind of thing that could be done using a desktop portal and permission model. But that would take someone with the time, desire, and prerequisite knowledge to build the required integrations. And further it would require buy-in from desktop maintainers to integrate the portal.

I'd imagine we're going to be stuck with running Discord unsandboxed for those features for a while.
